# Uygulama adı
spring.application.name=notify-hub

# PostgreSQL bağlantısı (docker-compose'daki ayarlarla aynı)
spring.datasource.url=jdbc:postgresql://localhost:5432/notifyhub
spring.datasource.username=notifyhub
spring.datasource.password=notifyhub123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA — tablo yapısını otomatik güncelle (sadece geliştirme için!)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Redis bağlantısı
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=redis123

# Port
server.port=8080